### ISSUE TITLE
Session is sometimes Unbound within rest client

### ISSUE THREAD

**Issue by CaedenPH** [sarthhh/asuka#4]
Sometimes `client_session` is unbound in the rest client. `client_session` kwarg is denoted as optional, however when it is not passed client_session is not bound. 

https://github.com/sarthhh/asuka/blob/master/asuka/rest/client.py#L51

**FIX**
Check for client session being `None` when the bot is initiated.

https://github.com/sarthhh/asuka/blob/master/asuka/bot.py#L80

**Comment by sarthhh** [comment]
> Sometimes `client_session` is unbound in the rest client. `client_session` kwarg is denoted as optional, however when it is not passed client_session is not bound. 
> 
> https://github.com/sarthhh/asuka/blob/master/asuka/rest/client.py#L51
> 
> **FIX**
> Check for client session being `None` when the bot is initiated.
> 
> https://github.com/sarthhh/asuka/blob/master/asuka/bot.py#L80

The `_session` attribute is not set for RESTClient object within the `__init__` when client_session is None, in that case  `RESTClient._create_session` method is called inside `Bot.start` method which adds an _session attribute to the class. 
 - https://github.com/sarthhh/asuka/blob/master/asuka/bot.py#L178-L179
 

I initially thought about adding a new session if client_session was None in the class `__init__` but creating ClientSessions inside non-async methods is getting deprecated so i just used the method above.

**Comment by CaedenPH** [comment]
@sarthhh 
You could create a decorator in which to start the bot from. Or you could create a task from the loop to create the global session from. Ideally, if the session is used in multiple places it would just be best to find a better way to initiate it within the bot class

**Comment by sarthhh** [comment]
Fixed the client_session issue in a patch.
